[package]
name = "tag_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
extendr-api = "0.7.1"
pyo3 = "0.23.4"
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
statrs = "0.18.0"
thiserror = "2.0.11"
